baseURL = 'http://0800ben.com/'
languageCode = 'en-gb'
title = '0800 BEN'
theme = ['custom', 'reveal-hugo']

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
