name: Build and Publish
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Hugo setup
          uses: peaceiris/actions-hugo@v2.6.0
        
        - name: Build the site
          run: hugo
        
        - name: Publish
          uses: JamesIves/github-pages-deploy-action@v4.4.3
          with:
              folder: public
              branch: live
